# Generated by Django 3.2.9 on 2021-12-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
